config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, except: :show
  resources :tenants, except: :show
  resources :locations, except: :show
  resources :floors, except: :show
  resources :rooms
  resources :desks, except: :show
  resources :limitations, except: :show
  resources :reservations, except: :show

  get "profile" => "profiles#show"
  patch "profile" => "profiles#update"
  put "profile" => "profiles#update"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/limitation.rb
# frozen_string_literal: true

class Limitation < ApplicationRecord
  self.implicit_order_column = :start_date

  after_save :remove_stale_reservations

  validates :name, uniqueness: true
  validates :name, length: { in: 2..50 }

  validates :end_date, comparison: { greater_than: :start_date }

  belongs_to :limitable, polymorphic: true, optional: true

  def remove_stale_reservations
    case limitable_type
    when "Tenant"
      reservations = Reservation.where("start_date >= ?", start_date).where("end_date <= ?", end_date).load_async
      reservations.each do |reservation|
        desk = Desk.find_by(id: reservation.desk_id)
        reservation.destroy if desk.room.floor.location.tenant.id == limitable_id
      end
    when "Location"
      reservations = Reservation.where("start_date >= ?", start_date).where("end_date <= ?", end_date).load_async
      reservations.each do |reservation|
        desk = Desk.find_by(id: reservation.desk_id)
        reservation.destroy if desk.room.floor.location.id == limitable_id
      end
    when "Floor"
      reservations = Reservation.where("start_date >= ?", start_date).where("end_date <= ?", end_date).load_async
      reservations.each do |reservation|
        desk = Desk.find_by(id: reservation.desk_id)
        reservation.destroy if desk.room.floor.id == limitable_id
      end
    when "Room"
      reservations = Reservation.where("start_date >= ?", start_date).where("end_date <= ?", end_date).load_async
      reservations.each do |reservation|
        desk = Desk.find_by(id: reservation.desk_id)
        reservation.destroy if desk.room.id == limitable_id
      end
    when "Desk"
      Reservation.where("start_date >= ?", start_date).where("end_date <= ?", end_date).where("desk_id = ?", limitable_id).destroy_all
    end
  end
end

app/controllers/limitations_controller.rb
# frozen_string_literal: true

class LimitationsController < ApplicationController
  before_action :set_limitation, only: [:edit, :update, :destroy]
  before_action :access_granted
  after_action :queue_cleanup, only: [:create, :update, :destroy]

  # GET /limitations
  def index
    @limitations = Limitation.all.order("start_date ASC").page(@page)
    respond_to do |format|
      format.html
      format.json { render json: Limitation.all }
    end
  end

  # GET /limitations/new
  def new
    @limitation = Limitation.new
  end

  # GET /limitations/1/edit
  def edit
  end

  # POST /limitations
  def create
    patched_params = patch_params limitation_params

    @limitation = Limitation.new(patched_params)

    if @limitation.save
      redirect_to limitations_path, notice: "Limitation was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /limitations/1
  def update
    patched_params = patch_params limitation_params

    if @limitation.update(patched_params)
      redirect_to limitations_path, notice: "Limitation was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /limitations/1
  def destroy
    @limitation.destroy

    redirect_to limitations_url, notice: "Limitation was successfully deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_limitation
      @limitation = Limitation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def limitation_params
      params.require(:limitation).permit(:page, :name, :start_date, :end_date)
    end

    def access_granted
      head(:forbidden) unless @current_role == "admin"
    end

    def queue_cleanup
      LimitationsCleanupJob.perform_later
    end
end

app/views/limitations/_form.html.haml
= simple_form_for @limitation do |f|
  .row
    .col-md-12
    
      = f.input :name
      = f.input :start_date, as: :datetime, html5: true
      = f.input :end_date, as: :datetime, html5: true

  = f.button :submit, class: 'btn btn-success'

app/views/limitations/edit.html.haml
%h3 Edit Limitation
%i.fa-solid.fa-circle-info
%p DateTimes will be transformed to the beginning of day and the end of day. E.g. an end date of 2099-12-31T13:00:00 becomes 2099-12-31T23:59:59.
= render 'form', limitation: @limitation

app/views/limitations/index.html.haml
%h2
  Limitations
  - if @current_role == "admin"
    = link_to 'New Limitation', new_limitation_path, class: 'btn btn-primary float-right'
%i.fa-solid.fa-circle-info
%p Limitations are polymorphic 1:1 relations. Meaning a limitation can be applied to different models (e.g. to a Tenant or a Room). You cannot assign a limitation more than once.
%i.fa-solid.fa-circle-info
%p Limitations are mighty. Handle with extreme care. If you re-assign a limitation, all reservations will be deleted that match the new assigment.
.clearfix
.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Name
        %th Start
        %th End
        %th Assigned to
    %tbody
      - @limitations.each do |limitation|
        %tr
          %td
            = limitation.name
          %td
            = limitation.start_date
          %td
            = limitation.end_date
          %td
            = limitation.limitable_type
            = limitation.limitable_id
          %td
            .d-flex.justify-content-end
              - if @current_role == "admin"
                = link_to 'Edit', edit_limitation_path(limitation), class: 'btn btn-sm btn-outline-info mr-2'
                = link_to 'Delete', limitation_path(limitation), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger'
.d-flex.justify-content-center.mt-3
  = paginate @limitations

app/views/limitations/new.html.haml
%h3 New Limitation
= render 'form', limitation: @limitation