config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, except: :show
  resources :tenants, except: :show
  resources :locations, except: :show
  resources :floors, except: :show
  resources :rooms
  resources :desks, except: :show
  resources :limitations, except: :show
  resources :reservations, except: :show

  get "profile" => "profiles#show"
  patch "profile" => "profiles#update"
  put "profile" => "profiles#update"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-dark.sticky-top.bg-dark.flex-md-nowrap.p-0
  = link_to root_path, class: 'navbar-brand col-sm-3 col-md-2 mr-0' do
    =image_tag "jumpseat_logo.png", style: 'height:25px;width:auto;'
    Jumpseat
  %ul.navbar-nav.px-3.full-width
    - if user_signed_in?
      %li.nav-item.text-nowrap
        = link_to "- logout", destroy_user_session_path, method: :delete, class: 'nav-link float-right'
        = link_to "#{current_user.first_name} #{current_user.last_name} (#{current_user.email}) -", profile_path, class: 'nav-link float-right'

app/views/shared/_sidebar.html.haml
%nav.col-md-2.d-md-block.bg-dark.sidebar
  .sidebar-sticky.pt-0.border-right
    %ul.nav.flex-column.list-group.list-group-flush.p-3
      = link_to root_path, class: 'list-group-item list-group-item-action' do
        %i.fa-solid.fa-chart-line
        Dashboard
      = link_to rooms_path, class: 'list-group-item list-group-item-action' do
        %i.fa-solid.fa-people-roof
        Rooms
      = link_to reservations_path, class: 'list-group-item list-group-item-action' do
        %i.fa-solid.fa-bookmark
        Reservations
      - if @current_role == "admin"
        %br
        = link_to tenants_path, class: 'list-group-item list-group-item-action' do
          %i.fa-solid.fa-sitemap
          Tenants
        = link_to locations_path, class: 'list-group-item list-group-item-action' do
          %i.fa-regular.fa-building
          Locations
        = link_to floors_path, class: 'list-group-item list-group-item-action' do
          %i.fa-solid.fa-stairs
          Floors
        = link_to desks_path, class: 'list-group-item list-group-item-action' do
          %i.fa-solid.fa-desktop
          Desks
        = link_to limitations_path, class: 'list-group-item list-group-item-action' do
          %i.fa-solid.fa-hand
          Limitations
        = link_to users_path, class: 'list-group-item list-group-item-action' do
          %i.fa-solid.fa-users
          Users
      - if @current_role == "admin"
        %br
        = link_to sidekiq_web_path, class: 'list-group-item list-group-item-action', target: '_blank' do
          %i.fa-solid.fa-arrow-up-right-from-square
          Queues
        = link_to './metrics', class: 'list-group-item list-group-item-action', target: '_blank' do
          %i.fa-solid.fa-arrow-up-right-from-square
          Metrics
      
    %ul.nav.flex-column.list-group.list-group-flush.p-3