config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, except: :show
  resources :tenants, except: :show
  resources :locations, except: :show
  resources :floors, except: :show
  resources :rooms
  resources :desks, except: :show
  resources :limitations, except: :show
  resources :reservations, except: :show

  get "profile" => "profiles#show"
  patch "profile" => "profiles#update"
  put "profile" => "profiles#update"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/desk.rb
# frozen_string_literal: true

class Desk < ApplicationRecord
  self.implicit_order_column = :name

  scope :limit_room, ->(room) { where("room_id = ?", room.id) }

  validate :position_in_room_unique

  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }
  validates :pos_x, comparison: { greater_than: 0 }
  validates :pos_y, comparison: { greater_than: 0 }
  validates :required_position, inclusion: { in: %w(trainee apprentice employee lead management), message: "%{value} is not a valid position" }

  # associations
  belongs_to :room, counter_cache: true
  has_many :limitations, as: :limitable
  has_many :reservations, dependent: :destroy

  def position_in_room_unique
    if id.nil?
      desks_with_same_pos = Desk.where("room_id = ?", room_id).where("pos_x = ?", pos_x).where("pos_y = ?", pos_y).all.count
    else
      desks_with_same_pos = Desk.where("id != ?", id).where("room_id = ?", room_id).where("pos_x = ?", pos_x).where("pos_y = ?", pos_y).all.count
    end
    errors.add(:pos_x, "position in room not unique / overlapping") if desks_with_same_pos > 0
  end
end

app/controllers/desks_controller.rb
# frozen_string_literal: true

class DesksController < ApplicationController
  before_action :set_desk, only: [:edit, :update, :destroy]
  before_action :access_granted

  # GET /desks
  def index
    @desks = Desk.includes(room: { floor: { location: :tenant } }).order("name ASC").all.page(@page)
    respond_to do |format|
      format.html
      format.json { render json: Desk.all }
    end
  end

  # GET /desks/new
  def new
    @desk = Desk.new
  end

  # GET /desks/1/edit
  def edit
  end

  # POST /desks
  def create
    @desk = Desk.new(desk_params)

    if @desk.save
      redirect_to desks_path, notice: "Desk was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /desks/1
  def update
    if @desk.update(desk_params)
      redirect_to desks_path, notice: "Desk was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /desks/1
  def destroy
    @desk.destroy

    redirect_to desks_url, notice: "Desk was successfully deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_desk
      @desk = Desk.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def desk_params
      params.require(:desk).permit(:page, :name, :room_id, :pos_x, :pos_y, :width, :height, :required_position, limitation_ids: [])
    end

    def access_granted
      head(:forbidden) unless @current_role == "admin"
    end
end

app/views/desks/_form.html.haml
= simple_form_for @desk do |f|
  .row
    .col-md-12
    
      = f.input :name
      = f.input :room_id, collection: Room.order("name ASC").all, label_method: :name, value_method: :id
      = f.input :pos_x
      = f.input :pos_y
      = f.input :required_position, collection: [:trainee, :apprentice, :employee, :lead, :management]
      = f.association :limitations, collection: Limitation.order("name ASC").all, as: :check_boxes, label_method: :name, value_method: :id, include_blank: false

  = f.button :submit, class: 'btn btn-success'

app/views/desks/edit.html.haml
%h3 Edit Desk
= render 'form', desk: @desk

app/views/desks/index.html.haml
%h2
  Desks
  - if @current_role == "admin"
    = link_to 'New Desk', new_desk_path, class: 'btn btn-primary float-right'
.clearfix
.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Name
        %th Tenant
        %th Location
        %th Floor
        %th Room
        %th X
        %th Y
        %th Required position
        %th #Reservations
    %tbody
      - @desks.each do |desk|
        %tr
          %td
            = desk.name
          %td
            = desk.room.floor.location.tenant.name
          %td
            = desk.room.floor.location.name  
          %td
            = desk.room.floor.name
          %td
            = link_to "#{desk.room.name}", room_path(:id => desk.room.id, :start_date => (DateTime.now.utc.beginning_of_day + 1.day).strftime("%Y-%m-%dT%H:%M"))
          %td
            = desk.pos_x
          %td
            = desk.pos_y
          %td
            = desk.required_position
          %td
            = desk.reservations_count
          %td
            .d-flex.justify-content-end
              - if @current_role == "admin"
                = link_to 'Edit', edit_desk_path(desk), class: 'btn btn-sm btn-outline-info mr-2'
                = link_to 'Delete', desk_path(desk), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger'
.d-flex.justify-content-center.mt-3
  = paginate @desks

app/views/desks/new.html.haml
%h3 New Desk
= render 'form', tenant: @tenant