config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"

Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :users, except: :show
  resources :tenants, except: :show
  resources :locations, except: :show
  resources :floors, except: :show
  resources :rooms
  resources :desks, except: :show
  resources :limitations, except: :show
  resources :reservations, except: :show

  get "profile" => "profiles#show"
  patch "profile" => "profiles#update"
  put "profile" => "profiles#update"

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => "/sidekiq"
  end

  # Defines the root path route ("/")
  root "dashboard#index"
end

app/models/room.rb
# frozen_string_literal: true

class Room < ApplicationRecord
  self.implicit_order_column = :name

  scope :limit_floor, ->(floor) { where("floor_id = ?", floor.id) }

  validates :name, uniqueness: true
  validates :name, length: { in: 2..20 }

  # associations
  belongs_to :floor, counter_cache: true
  has_many :desks, dependent: :destroy
  has_many :limitations, as: :limitable
end

app/controllers/rooms_controller.rb
# frozen_string_literal: true

class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  before_action :access_granted, only: [:new, :edit, :create, :update, :destroy]

  # GET /rooms
  def index
    @rooms = Room.includes(floor: { location: :tenant }).order("name ASC").all.page(@page)
    respond_to do |format|
      format.html
      format.json { render json: Room.all }
    end
  end

  # GET /rooms/1
  def show
    params.permit(:id, :start_date)
    @start_date = DateTime.strptime(params["start_date"], "%Y-%m-%dT%H:%M").beginning_of_day
    end_date = @start_date.end_of_day

    desks = Desk.where("room_id = ?", @room.id).order("pos_x, pos_y ASC").all.load_async
    desk_ids = desks.map(&:id)
    reservations = Reservation.where(desk_id: desk_ids).where("start_date >= ?", @start_date).where("end_date <= ?", end_date).group(:desk_id).count

    @map = {}
    @map["width"] = 0
    @map["height"] = 0
    @map["desks"] = []
    desks.each do |desk|
      status = "available"
      status = "unavailable" if (!reservations[desk.id].nil?) && (reservations[desk.id] > 0)
      if status == "available"
        # try to validate a reservation
        reservation = Reservation.new(start_date: @start_date, end_date:, user: current_user, desk:)
        status = "unavailable" if !reservation.valid?
      end

      entry = {}
      entry["id"] = desk.id
      entry["name"] = desk.name
      entry["pos_x"] = desk.pos_x
      entry["pos_y"] = desk.pos_y
      entry["status"] = status

      @map["desks"].push(entry)

      @map["width"] = desk.pos_x if desk.pos_x >= @map["width"]
      @map["height"] = desk.pos_y if desk.pos_y >= @map["height"]
    end

    # we add one as a border here
    @map["width"] = @map["width"] + 1
    @map["height"] = @map["height"] + 1
    @map
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  def create
    @room = Room.new(room_params)

    if @room.save
      redirect_to rooms_path, notice: "Room was successfully created."
    else
      render :new
    end
  end

  # PATCH/PUT /rooms/1
  def update
    if @room.update(room_params)
      redirect_to rooms_path, notice: "Room was successfully updated."
    else
      render :edit
    end
  end

  # DELETE /rooms/1
  def destroy
    @room.destroy

    redirect_to rooms_url, notice: "Room was successfully deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def room_params
      params.require(:room).permit(:page, :name, :floor_id, limitation_ids: [])
    end

    def access_granted
      head(:forbidden) unless @current_role == "admin"
    end
end

app/views/rooms/_form.html.haml
= simple_form_for @room do |f|
  .row
    .col-md-12
    
      = f.input :name
      = f.input :floor_id, collection: Floor.order("name ASC").all, label_method: :name, value_method: :id
      = f.association :limitations, collection: Limitation.order("name ASC").all, as: :check_boxes, label_method: :name, value_method: :id, include_blank: false

  = f.button :submit, class: 'btn btn-success'

app/views/rooms/edit.html.haml
%h3 Edit Room
= render 'form', room: @room

app/views/rooms/index.html.haml
%h2
  Rooms
  - if @current_role == "admin"
    = link_to 'New Room', new_room_path, class: 'btn btn-primary float-right'
.clearfix
.table-responsive
  %table.table.table-striped.table-hover
    %thead
      %tr
        %th Name
        %th Tenant
        %th Location
        %th Floor
        %th #Desks
    %tbody
      - @rooms.each do |room|
        %tr
          %td
            = link_to "#{room.name}", room_path(:id => room.id, :start_date => (DateTime.now.utc.beginning_of_day + 1.day).strftime("%Y-%m-%dT%H:%M"))
          %td
            = room.floor.location.tenant.name
          %td
            = room.floor.location.name  
          %td
            = room.floor.name
          %td
            = room.desks_count
          %td
            .d-flex.justify-content-end
              - if @current_role == "admin"
                = link_to 'Edit', edit_room_path(room), class: 'btn btn-sm btn-outline-info mr-2'
                = link_to 'Delete', room_path(room), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger'
.d-flex.justify-content-center.mt-3
  = paginate @rooms

app/views/rooms/new.html.haml
%h3 New Room
= render 'form', tenant: @tenant

app/views/rooms/show.html.haml
%h2
  Room
  = @room.name

= simple_form_for(@room, method: :get, url: room_path(:id => @room.id)) do |f|
  = f.input :start_date, as: :datetime, html5: true, input_html: { name: "start_date", value: @start_date }
  = f.button :submit, 'Change date', class: 'btn btn-success'

%br
%br
%i.fa-solid.fa-circle-info
%p If you see a lot of red, there might be a reason. Most likely you already reserved a desk for that date or a limitation is in effect (e.g. holidays).

%table.table-bordered
  - (0..@map["height"]).each do |i|
    %tr{ :style => "height: 100px" }
      - (0..@map["width"]).each do |j|
        %td{ :style => "width: 100px" }
          - @map["desks"].each do |desk|
            - if (desk["pos_x"] == j) && (desk["pos_y"] == i)
              - if desk["status"] == "available"
                %div{ :style => "background-color: #aeff9c; width: 100px; height: 100px; padding: 0; margin: 0"}
                  = desk["name"]
                  = simple_form_for Reservation.new do |f|
                    = f.input :desk_id, as: :hidden, input_html: { value: desk["id"] }
                    = f.input :start_date, as: :hidden, input_html: { value: @start_date }
                    = f.input :user_id, as: :hidden, input_html: { value: @current_user.id }
                    = f.button :submit, 'Reserve', class: 'btn btn-success w-100 h-100'
              - else
                %div{ :style => "background-color: #ff9c9c; width: 100px; height: 100px; padding: 0; margin: 0"}
                  = desk["name"]